# Generated by Django 5.0.7 on 2024-07-12 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
    ]
