# Generated by Django 5.0.7 on 2024-07-12 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_remove_review_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='review',
            name='rating',
            field=models.CharField(blank=True, choices=[('1', 'One Star'), ('2', 'Two Star'), ('3', 'Three Star'), ('4', 'Four Star'), ('5', 'Five Star')], max_length=10, null=True),
        ),
    ]
