# Generated by Django 5.0.7 on 2024-07-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_category_slug_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='borrowing_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
