# Generated by Django 5.0.7 on 2024-07-13 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_borrowinghistory_returned_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowinghistory',
            name='returned_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
