# Generated by Django 5.0.7 on 2024-07-13 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_borrowinghistory_returned_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowinghistory',
            name='returned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
