# Generated by Django 5.0.7 on 2024-07-13 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_borrowinghistory_returned_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowinghistory',
            name='can_review',
            field=models.BooleanField(default=False),
        ),
    ]
